version: '3.8'

services:
  mcp-server:
    build: .
    volumes:
      - ./test_files:/app/test_files
      - ./output:/app/output
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - LOG_LEVEL=INFO
    stdin_open: true
    tty: true 